bt_firmware_files := \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8703as_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8703as_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8703bs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8703bs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8703cs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8703cs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723a_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723a_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723as_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723as_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723b_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723b_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723bs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723bs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723bs_VQ0_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723bs_VQ0_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723bu_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723c_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723cs_cg_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723cs_cg_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723cs_vf_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723cs_vf_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723cs_xx_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723cs_xx_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723d_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723d_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723ds_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8723ds_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761a_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761at_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761at_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761au8192ee_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761au8812ae_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761au_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761aw8192eu_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761aw8192eu_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8821a_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8821a_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8821as_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8821as_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8821c_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8821c_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8821c_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8821cs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8821cs_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8821cs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822b_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822b_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822bs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822bs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822c_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822c_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822c_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822cs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822cs_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822cs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761b_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761b_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761b_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761bt_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761bt_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8761bt_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8725a_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8725a_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8733b_8723f_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8733b_8723f_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8733b_8723f_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8733bs_8723fs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8733bs_8723fs_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8733bs_8723fs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852as_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852as_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852as_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852au_config_vendor \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852au_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852au_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852bs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852bs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852bu_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852bu_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852cu_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852cu_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852cs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8852cs_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822e_8822c_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822e_8822c_fw \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822es_8822cs_config \
	vendor/amlogic/common/wifi_bt/bluetooth/realtek/rtkbt/Firmware/BT/rtl8822es_8822cs_fw

PRODUCT_COPY_FILES += $(call copy-files,$(bt_firmware_files),$(TARGET_COPY_OUT_VENDOR)/firmware)
