LOCAL_PATH := $(my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := mlanutl
LOCAL_LICENSE_KINDS := SPDX-license-identifier-GPL-2.0
LOCAL_LICENSE_CONDITIONS := restricted
LOCAL_SRC_FILES := mlanutl.c
LOCAL_CFLAGS += -Wall -DUSERSPACE_32BIT_OVER_KERNEL_64BIT
LOCAL_PROPRIETARY_MODULE := true
include $(BUILD_EXECUTABLE)
